const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const DEFAULT_ERROR = 500;
const STATUS_OK = 200;

module.exports = {
  NOT_FOUND_ERROR,
  BAD_REQUEST_ERROR,
  DEFAULT_ERROR,
  STATUS_OK,
};
